baseurl: "/"
languageCode: "zh-cn"
# defaultContentLanguage: "en"
defaultContentLanguage: "zh"
title: "生息"
theme: "hugo-prose"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"
paginate: 20
# publishdir: "public"

permalinks:
  post: "/p/:06/:01/:slug/"
  note: "/n/:06/:01/:slug/"
  slides: "/s/:06/:01/:slug/"
  digest: "/d/:06/:01/:slug/"

outputs:
  home: [html, rss, json]

# some menu items were added via the `menu` option in YAML in posts
menu:
  header:
    - name: 搜索
      url: "#"
      identifier: menu-search
    - name: 订阅
      url: "index.xml"
  footer:
    - name: 分类
      url: "/categories/"
      weight: 2
      pre: "optional"
    - name: 标签
      url: "/tags/"
      weight: 3
      pre: "optional"
    - name: 编辑
      url: "#"
      weight: 4
      identifier: "menu-edit"
    - name: 顶部
      url: "#"

params:
  homePosts: 10
  digePosts: 12
  mainSections: ["post", "note", "slides"]
  digeSections: ["digest"]
  editLink: "https://github.com/pftz/pftz/edit/master/content/"
  summaryLength: 120
  authorDelimiter: ", "
  pageFeatures: [+sidenotes]
  description: >
    EcoK - 生息.
  footer: >
    &copy; EcoK (2021 - 2021)
  license: >
    本文文字和图表使用[知识共享许可协议
    CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)，[源文件](https://github.com/pftz/pftz)采用
    MIT 协议。

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
